services:
  billdb-go:
    build:
      context: .
      dockerfile: ./build/docker/Dockerfile
      target: base
    command: go run ./cmd/server/main.go
    ports:
      - "8080:1323"
    environment:
      - BILLDB_DB_PATH=/billdb/data/bills.db
    volumes:
      - ../billdb-docker-test/data:/billdb/data
      - ./web/templates:/billdb/templates
      - ./web/static:/billdb/static
      - ./cmd:/billdb/cmd
      - ./internal/:/billdb/internal
    restart: unless-stopped

