services:
  billdb-go:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    command: go run ./cmd/server/main.go
    ports:
      - "8080:1323"
    volumes:
      - ./web/templates:/server/templates
      - ./web/static:/server/static
      - ./cmd:/server/cmd
      - ./internal/:/server/internal
      - ../billdb-docker-test/:/server/data
    restart: unless-stopped

